export enum TABLES {
    USERS = 'users',
    REFRESHTOKENS = 'refreshtokens',
    ROLES = 'roles',
    USERS_ROLES = 'users_roles',
    CITIES = 'cities',
    ADDRESSES = 'addresses',
    USERS_ADDRESSES = 'users_addresses',
    CUSTOMER_TYPES = 'customers_types',
    CUSTOMERS = 'customers',
    EMPLOYEES = 'employees',
    SUPPLIERS = 'suppliers',
    ESTIMATIONS = 'estimations',
    TARIFFS = 'tariffs',
    CONTRACT_STATUSES = 'contract_statuses',
    CONTRACTS = 'contracts',
    CUSTOMERS_CONTRACTS = 'customers_contracts',
    PLANNING_STATUSES = 'planning_statuses',
    PLANNINGS = 'plannings',
    METERS = 'meters',
    INDEXED_VALUES = 'indexed_values',
    CONSUMPTIONS = 'consumptions',
    CONTRACTS_METERS = 'contracts_meters',
    INVOICE_STATUSES = 'invoice_statuses',
    INVOICE_TYPES = 'invoice_types',
    INVOICES = 'invoices',
    INVOICES_STATUSES = 'invoices_statuses',
}
